apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-new
  template:
    metadata:
      labels:
        app: client-new
    spec:
      containers:
      - name: client-new
        image: debolek/client_new:latest
